version: '3'
volumes: #When the container is deleted this volumes stay!
  cache:
  log:
  vendor:

services:
  # apache:
  #   build: ./apache # Builds from this location (Dockerfile)
  #   container_name: sf2_apache
  #   ports:
  #     - 81:80
  #   volumes:
  #     - ./config/vhosts:/etc/apache2/sites-enabled
  #     - ./code/app/cache:/home/wwwroot/sf2/code/app/cache # Overrides cache folder
  #     - ./code/app/logs:/home/wwwroot/sf2/code/app/logs # Overrides log folder
  #     - ./code/vendor:/home/wwwroot/sf2/code/vendor # Overrides vendor folder
  #     - ./code:/home/wwwroot/sf2/code
  #   depends_on:
  #     - php

  nginx:
    image: nginx:latest
    container_name: sf2_nginx
    ports:
        - "81:80"
  #     - "443:443"
    volumes:
        - ./code:/home/wwwroot/sf2/code:rw # With read / write access
        - ./log:/webserver/log:rw # With read / write access
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # With read-only access
    depends_on:
        - php

  mysql:
    image: mysql:8
    container_name: sf2_mysql
    volumes:
      - ./data/db:/var/lib/mysql
    command:
      - "--innodb-flush-method=littlesync"
      - "--innodb-use-native-aio=OFF"
      - "--log_bin=ON"
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf2
      MYSQL_USER: sf2
      MYSQL_PASSWORD: sf2

  php:
    build: ./php  # Builds from this location (Dockerfile)
    container_name: sf2_php
    volumes:
      - ./code:/home/wwwroot/sf2/code
    environment:
      - maildev_host=sf2_maildev
      - XDEBUG_ENABLE="true"
      - DOCKERHOST=host.docker.internal
    depends_on:
#     - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf2_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80
    links:
      - mysql

#  maildev:
#    image: djfarrelly/maildev
#    container_name: sf2_maildev
#    ports:
#      - 8001:80
