<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    const LATEST_POST_COUNT = 10;

    /**
     * Find latest
     * 
     * @param int $num
     * 
     * @return array
     */
    public function findLatest($count = null) {
        $count = $count ?? self::LATEST_POST_COUNT;
        $qb = $this->getQueryBuilder()
                   ->orderBy('p.createdAt', 'desc')
                   ->setMaxResults($count);

        return $qb->getQuery()->getResult();
    }
    
    private function getQueryBuilder() {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('ModelBundle:Post')
                 ->createQueryBuilder('p');

        return $qb;
    }
}
