blog_model:
    resource: "@BlogModelBundle/Controller/"
    type:     annotation
    prefix:   /

blog_core:
    resource: "@BlogCoreBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

yoda_event:
    resource: "@YodaEventBundle/Resources/config/routing.yml"
    prefix:   /